CREATE TABLE IF NOT EXISTS city_info (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  cod varchar(3) null,
  message integer null,
  cnt integer null,
  city_id integer null,
  city_name varchar(100) null,
  coord_lat decimal null,
  coord_lon decimal null,
  country varchar(60) null,
  population integer null,
  timezone integer null,
  sunrise integer null,
  sunset integer null,
  PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS city_weather (
  id integer REFERENCES city_info(id),
  dt integer null,
  main_feels_like decimal null,
  main_temp_min decimal null,
  main_temp_max decimal null,
  main_pressure integer null,
  main_sea_level integer null,
  main_grnd_level integer null,
  main_humidity integer null,
  main_temp_kf decimal null,
  weather_id integer null,
  weather_main varchar(20) null,
  weather_description varchar(50) null,
  weather_icon varchar(10) null,
  clouds_all integer null,
  wind_speed decimal null,
  wind_deg integer null,
  wind_gust decimal null,
  visibility integer null,
  pop integer null,
  sys_pod varchar(5) null,
  dt_txt varchar(25) null
);

